### ISSUE TITLE
Building on NixOS using stack fails

### ISSUE THREAD

**Issue by freeman42x** [lamdu/nodejs-exec#1]
[neo@nixos:~/Forks/nodejs-exec]$ stack install --nix

    Warning: File listed in nodejs-exec.cabal file does not exist: bin/node
    nodejs-exec-0.1.0.0: build (lib)

    Warning: Package nodejs-exec uses a custom Cabal build, but does not use a custom-setup stanza
    Preprocessing library nodejs-exec-0.1.0.0...
    build_node.sh: line 8: node: command not found
    Building nodejs from source
    fatal: destination path 'node' already exists and is not an empty directory.
    /usr/bin/env: 'python': No such file or directory
    /bin/sh: python: command not found
    make: python: Command not found
    make: python: Command not found
    make: python: Command not found
    make: python: Command not found
    make: python: Command not found
    make: python: Command not found
    make: python: Command not found
    make: python: Command not found
    make: python: Command not found
    Makefile:84: *** Missing or stale config.gypi, please run ./configure.  Stop.
    cp: cannot stat 'node/node': No such file or directory

    --  While building custom Setup.hs for package nodejs-exec-0.1.0.0 using:
        /home/neo/Forks/nodejs-exec/.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0 build lib:nodejs-exec --ghc-options " -ddump-hi -ddump-to-file"
        Process exited with code: ExitFailure 1

    [neo@nixos:~/Forks/nodejs-exec]$ node --version
    v8.9.4

NodeJS is installed yet it can't find it: ` build_node.sh: line 8: node: command not found`

On NixOS node executable is located under `/run/current-system/sw/bin/node` instead of `bin/node` so other changes would probably need to be made to account for that.

**Comment by yairchu** [comment]
It looks like even though `node` is available in your system, it complains about failing [this line](https://github.com/lamdu/nodejs-exec/blob/master/build_node.sh#L8) with `node: command not found`. Perhaps `stack install --nix` runs things with different paths and that's why it can't find it? What happens if you do `stack install` without the `--nix` flag?

**Comment by freeman42x** [comment]
It build fine if adding to yaml file:

    nix:
      enable: true
      packages:
      - nodejs-8_x
      - which

**Comment by freeman42x** [comment]
Running just stack install without nix gives:

    /bin/bash: bad interpreter: No such file or directory

**Comment by yairchu** [comment]
I notice that you wrote `enable: true` above but `enable: false` in the pull request, so just making sure - is the one from the pull request the correct one?

**Comment by freeman42x** [comment]
@yairchu The one from the pull-request is correct. Users should run `stack install --nix`, otherwise by default it would try to install with nix.
